pipeline{
    agent any

    options {
      timeout(time: 2, unit: 'HOURS') //Set a timeout period for the Pipeline run, after which Jenkins should abort the Pipeline
      disableConcurrentBuilds() //Disallow concurrent executions of the Pipeline
      timestamps() //Prepend all console output generated by the Pipeline run with the time at which the line was emitted
      buildDiscarder(logRotator(numToKeepStr:'50', artifactNumToKeepStr: '10')) //Persist artifacts and console output for the specific number of recent Pipeline runs

    }

    parameters {

      choice(
          name: 'DEPLOY',
          choices: ['DELTA-DEPLOY','FULL-DEPLOY','NO-DEPLOY'],
          description: 'Chooseperform delta or full or No deployment')
      booleanParam(
          name: 'SFDX_CHECK_ONLY',
          defaultValue: true,
          description: 'If true, will validate deployment, but not save to the org')
      choice(
          name: 'SFDX_TEST_LEVEL',
          choices: ['NoTestRun','RunSpecifiedTests','RunLocalTests','RunAllTestsInOrg'],
          description: 'Sets the Apex test level during deployment. The first value is the default.')
      string(
          name: 'DELTA_DEPLOY_PREV_COMMIT_REF',
          defaultValue: "",
          description: 'If not blank, use this commit ref to compare diffs with instead of a previous CI/CD build')
      booleanParam(
          name: 'DELTA_DEPLOY_DISPLAY_DIFF_FILES',
          defaultValue: true,
          description: 'If true, will display the list added/changed files')

    }

  environment{
    SF_CONSUMER_KEY           = "${env.CONNECTED_APP_CONSUMER_KEY_DH}"
    SERVER_KEY_CREDENTALS_ID  = "${env.JWT_CRED_ID_DH}"
    PACKAGE_NAME              = '00D2w000001eI5iEAE'
    SF_INSTANCE_URL           = "${env.SFDC_HOST_DH}"
    SF_USERNAME               = "${env.HUB_ORG_DH}"
    PACKAGE_VERSION           = ''
    server_key_file           = credentials("${env.JWT_CRED_ID_DH}")
    toolbelt_SF               = tool 'toolbelt-sf'
    toolbelt_SFDX             = tool 'toolbelt-sfdx'

  }

  stages{                                                                               
    stage('Checkout'){
          steps{
            checkout scm
            echo 'checkout scm'
          }
    }

    stage('Install sgd-git-delta plugin') {
            steps {
                script {
                    bat script: "\"${toolbelt_SFDX}\" plugins:install sfdx-git-delta"
                }
            }
        }

    stage('Generate Diff'){
          steps{
            bat script: "\"${toolbelt_SFDX}\" sgd:source:delta -f ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT} -o . --loglevel info"
          }
    }

    stage('Authenticate with Salesforce'){
          
      steps{

        withCredentials([file(credentialsId: "${SERVER_KEY_CREDENTALS_ID}", variable: 'serverkey_file')]) {

          bat script: "\"${toolbelt_SF}\" force:auth:jwt:grant --client-id ${SF_CONSUMER_KEY} --username ${SF_USERNAME} --jwt-key-file \"${serverkey_file}\" --set-default --instance-url ${SF_INSTANCE_URL}"        
        }
  
      }
    }

    stage('Validate Deployment - Dry Run'){

      when{
        allOf{
          expression { return params.SFDX_CHECK_ONLY }
          expression { return params.SFDX_TEST_LEVEL == 'NoTestRun'}
        }
      }
          
      steps{

        echo "Validating Deployment" 
        bat script: "\"${toolbelt_SF}\" project deploy start --dry-run --target-org ${SF_USERNAME}"  
  
      }
    }

    stage('Run Apex Tests'){

      when{
        allOf{
          expression { return params.SFDX_CHECK_ONLY }
          expression { return params.SFDX_TEST_LEVEL != 'NoTestRun' }
        }
      }
          
      steps{

        echo "Run Apex Tests: ${params.SFDX_TEST_LEVEL}" 

        bat script: "\"${toolbelt_SF}\" project deploy start --dry-run --test-level ${params.SFDX_TEST_LEVEL} -w 180 -o ${SF_USERNAME}"       
  
      }
    }

    stage('Deploy'){

      when{
          expression { return params.SFDX_CHECK_ONLY == false }
      }
          
      steps{
          echo "Begin Deployment" 
          bat script: "\"${toolbelt_SF}\" project deploy start -d ${env.WORKSPACE} --target-org ${SF_USERNAME}"
          echo "Deployed"        
  
      }
    }
  }

  post{
    always{
      echo 'Always logout SF Org...'
      bat script: "\"${toolbelt_SF}\" org logout --target-org ${SF_USERNAME} --no-prompt"

      echo "Current build commit ${env.GIT_COMMIT}"
      echo "Previous successful commit ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT}"

      // script{
      //   res = bat (returnStdout : true, script: "git diff ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT} ${env.GIT_COMMIT} --name-only > delta.txt").trim()

      //   echo "output : ${res}"
      // }

    }
    // success {
    //     setBuildStatus("Build succeeded", "SUCCESS");
    // }
    // failure {
    //     setBuildStatus("Build failed", "FAILURE");
    // }
  }
}